version: '3'
services:
  master:
    build: ./jenkins-master
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net

  ui:
    build: ./ui
    ports:
      - '3000:3000'
    depends_on:
      - api
    networks:
      - jenkins-net
  api:
    build: ./api
    ports:
      - '9000:9000'
    depends_on:
      - mongo
    networks:
      - jenkins-net

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - jenkins-net
  
volumes:
  jenkins-log:
  jenkins-data:
networks:
  jenkins-net: